CONFIG_NAME: interop
PRESET_BASE: interop

# Genesis
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1
MIN_GENESIS_TIME: 1782431338
GENESIS_FORK_VERSION: 0x20000089
GENESIS_DELAY: 0

# Forking — all forks active from epoch 0
ALTAIR_FORK_VERSION: 0x20000090
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x20000092
CAPELLA_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x20000093
DENEB_FORK_EPOCH: 0
ELECTRA_FORK_VERSION: 0x20000094
ELECTRA_FORK_EPOCH: 0
FULU_FORK_VERSION: 0x20000095
FULU_FORK_EPOCH: 0
GLOAS_FORK_VERSION: 0x20000096
GLOAS_FORK_EPOCH: 18446744073709551615

# Time
SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 6
SECONDS_PER_ETH1_BLOCK: 1
ETH1_FOLLOW_DISTANCE: 0

# Validator
EJECTION_BALANCE: 16000000000
MIN_PER_EPOCH_CHURN_LIMIT: 4
CHURN_LIMIT_QUOTIENT: 32

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242

# Networking
DOMAIN_BEACON_PROPOSER: 0x00000000
DOMAIN_BEACON_ATTESTER: 0x01000000
